# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.6 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================




prefix = /usr
exec_prefix = ${prefix}
datarootdir = ${prefix}/share
INSTALL = /usr/bin/install -c
EXEEXT = 
WINDRES = 
SETFILE = 
STRIP = strip
NM = nm
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_DIR = $(INSTALL) -d
BK_DEPS = /home/leonti/usa/estes/bk-deps
srcdir = .
bindir = ${exec_prefix}/bin
datadir = ${datarootdir}
LIBS = 
LDFLAGS_GUI = 
CXX = g++
CXXFLAGS =  -I/usr/lib64/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread
CPPFLAGS = 
LDFLAGS =  -L/usr/lib64 -pthread   -L/usr/lib64   -lwx_gtk2u_richtext-2.8 -lwx_gtk2u_aui-2.8 -lwx_gtk2u_xrc-2.8 -lwx_gtk2u_qa-2.8 -lwx_gtk2u_html-2.8 -lwx_gtk2u_adv-2.8 -lwx_gtk2u_core-2.8 -lwx_baseu_xml-2.8 -lwx_baseu_net-2.8 -lwx_baseu-2.8 

### Variables: ###

DESTDIR = 
ESTES_CXXFLAGS = -I/usr/include/mysql -I/usr/include/mysql++ -Wall $(CPPFLAGS) \
	$(CXXFLAGS)
ESTES_OBJECTS =  \
	$(__estes___win32rc) \
	estes_settings.o \
	estes_add_zero.o \
	estes_editmenu.o \
	estes_dish_props.o \
	estes_restaurant_posApp.o \
	estes_taxes.o \
	estes_wx_std.o \
	estes_product_stats.o \
	estes_prog_set_panel.o \
	estes_perif_set_panel.o \
	estes_add_item.o \
	estes_payment.o \
	estes_perif.o \
	estes_waiter_choose.o \
	estes_display_settings.o \
	estes_db_set_panel.o \
	estes_stats_today.o \
	estes_cash.o \
	estes_backup.o \
	estes_workers.o \
	estes_restaurant_posMain.o

### Conditionally set variables: ###

#CXXC = $(CXX)
CXXC = $(BK_DEPS) $(CXX)
__estes___mac_setfilecmd = @true
#__estes___mac_setfilecmd = \
#	$(SETFILE) -t APPL estes$(EXEEXT)
COND_PLATFORM_OS2_1___estes___os2_emxbindcmd = $(NM) estes$(EXEEXT) | if grep -q \
	pmwin.763 ; then emxbind -ep estes$(EXEEXT) ; fi
#__estes___os2_emxbindcmd = $(COND_PLATFORM_OS2_1___estes___os2_emxbindcmd)
#__estes___win32rc = estes_resource_rc.o

### Targets: ###

all: estes$(EXEEXT)

install: install_estes
	$(INSTALL_DIR) $(DESTDIR)$(datadir)/estes
	(cd $(srcdir)/src ; $(INSTALL_DATA)  ../share/estes/table_schema.sql $(DESTDIR)$(datadir)/estes)
	$(INSTALL_DIR) $(DESTDIR)$(datadir)
	for f in locale/pl/LC_MESSAGES/estes.mo locale/es/LC_MESSAGES/estes.mo locale/ru/LC_MESSAGES/estes.mo; do \
	if test ! -d $(DESTDIR)$(datadir)/`dirname $$f` ; then \
	$(INSTALL_DIR) $(DESTDIR)$(datadir)/`dirname $$f`; \
	fi; \
	$(INSTALL_DATA) share/$$f $(DESTDIR)$(datadir)/$$f; \
	done
	$(INSTALL_DIR) $(DESTDIR)$(datadir)/applications
	(cd $(srcdir)/src ; $(INSTALL_DATA)  estes.desktop $(DESTDIR)$(datadir)/applications)
	$(INSTALL_DIR) $(DESTDIR)$(datadir)/pixmaps
	(cd $(srcdir)/src ; $(INSTALL_DATA)  estes.png $(DESTDIR)$(datadir)/pixmaps)

uninstall: uninstall_estes
	(cd $(DESTDIR)$(datadir)/estes ; rm -f table_schema.sql)
	for f in locale/pl/LC_MESSAGES/estes.mo locale/es/LC_MESSAGES/estes.mo locale/ru/LC_MESSAGES/estes.mo; do \
	rm -f $(DESTDIR)$(datadir)/$$f; \
	done
	(cd $(DESTDIR)$(datadir)/applications ; rm -f estes.desktop)
	(cd $(DESTDIR)$(datadir)/pixmaps ; rm -f estes.png)

install-strip: install
	$(STRIP) $(DESTDIR)$(bindir)/estes$(EXEEXT)

clean: 
	rm -rf ./.deps ./.pch
	rm -f ./*.o
	rm -f estes$(EXEEXT)

distclean: clean
	rm -f config.cache config.log config.status bk-deps bk-make-pch shared-ld-sh Makefile

estes$(EXEEXT): $(ESTES_OBJECTS) $(__estes___win32rc)
	$(CXX) -o $@ $(ESTES_OBJECTS)   $(LDFLAGS_GUI) $(LDFLAGS)  -lmysqlpp -lmysqlclient $(LIBS)
	
	$(__estes___mac_setfilecmd)
	$(__estes___os2_emxbindcmd)

install_estes: estes$(EXEEXT)
	$(INSTALL_DIR) $(DESTDIR)$(bindir)
	$(INSTALL_PROGRAM) estes$(EXEEXT) $(DESTDIR)$(bindir)

uninstall_estes: 
	rm -f $(DESTDIR)$(bindir)/estes$(EXEEXT)

estes_resource_rc.o: $(srcdir)/src/res/resource.rc
	$(WINDRES) -i$< -o$@  --include-dir /usr/include/mysql --include-dir /usr/include/mysql++

estes_settings.o: $(srcdir)/src/settings.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/settings.cpp

estes_add_zero.o: $(srcdir)/src/add_zero.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/add_zero.cpp

estes_editmenu.o: $(srcdir)/src/editmenu.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/editmenu.cpp

estes_dish_props.o: $(srcdir)/src/dish_props.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/dish_props.cpp

estes_restaurant_posApp.o: $(srcdir)/src/restaurant_posApp.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/restaurant_posApp.cpp

estes_taxes.o: $(srcdir)/src/taxes.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/taxes.cpp

estes_wx_std.o: $(srcdir)/src/wx_std.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/wx_std.cpp

estes_product_stats.o: $(srcdir)/src/product_stats.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/product_stats.cpp

estes_prog_set_panel.o: $(srcdir)/src/prog_set_panel.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/prog_set_panel.cpp

estes_perif_set_panel.o: $(srcdir)/src/perif_set_panel.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/perif_set_panel.cpp

estes_add_item.o: $(srcdir)/src/add_item.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/add_item.cpp

estes_payment.o: $(srcdir)/src/payment.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/payment.cpp

estes_perif.o: $(srcdir)/src/perif.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/perif.cpp

estes_waiter_choose.o: $(srcdir)/src/waiter_choose.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/waiter_choose.cpp

estes_display_settings.o: $(srcdir)/src/display_settings.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/display_settings.cpp

estes_db_set_panel.o: $(srcdir)/src/db_set_panel.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/db_set_panel.cpp

estes_stats_today.o: $(srcdir)/src/stats_today.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/stats_today.cpp

estes_cash.o: $(srcdir)/src/cash.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/cash.cpp

estes_backup.o: $(srcdir)/src/backup.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/backup.cpp

estes_workers.o: $(srcdir)/src/workers.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/workers.cpp

estes_restaurant_posMain.o: $(srcdir)/src/restaurant_posMain.cpp
	$(CXXC) -c -o $@ $(ESTES_CXXFLAGS) $(srcdir)/src/restaurant_posMain.cpp


# Include dependency info, if present:
-include ./.deps/*.d

.PHONY: all install uninstall clean distclean install_estes uninstall_estes
